// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIj6PodA6vDABZd_NpNeP9osDgzjKV0Wo',
    appId: '1:580033201098:web:a6f0de82f2d93b031f4533',
    messagingSenderId: '580033201098',
    projectId: 'ase-project-d7b70',
    authDomain: 'ase-project-d7b70.firebaseapp.com',
    storageBucket: 'ase-project-d7b70.appspot.com',
    measurementId: 'G-EHPCCLR1F7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX5BUf-NTrgS2FxjY8Oq4BlzXOuW3HEI8',
    appId: '1:580033201098:android:1dabb78a45f7365c1f4533',
    messagingSenderId: '580033201098',
    projectId: 'ase-project-d7b70',
    storageBucket: 'ase-project-d7b70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj5UN5WtbZEqZ1-vuITj8BbKXXEXORZRE',
    appId: '1:580033201098:ios:e403735b86b3c0891f4533',
    messagingSenderId: '580033201098',
    projectId: 'ase-project-d7b70',
    storageBucket: 'ase-project-d7b70.appspot.com',
    androidClientId: '580033201098-3kbh4gjf3fsoikjvapd2k3bdjqmkdgmo.apps.googleusercontent.com',
    iosClientId: '580033201098-ug1d6fbjs2sj8hq0gu2bl4adrf4fef27.apps.googleusercontent.com',
    iosBundleId: 'com.maven.market.mac.mavenMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj5UN5WtbZEqZ1-vuITj8BbKXXEXORZRE',
    appId: '1:580033201098:ios:e403735b86b3c0891f4533',
    messagingSenderId: '580033201098',
    projectId: 'ase-project-d7b70',
    storageBucket: 'ase-project-d7b70.appspot.com',
    androidClientId: '580033201098-3kbh4gjf3fsoikjvapd2k3bdjqmkdgmo.apps.googleusercontent.com',
    iosClientId: '580033201098-ug1d6fbjs2sj8hq0gu2bl4adrf4fef27.apps.googleusercontent.com',
    iosBundleId: 'com.maven.market.mac.mavenMarket',
  );
}
